### ISSUE TITLE
Error: File "./tools/liquidity/liquidNamespace.ml" 

### ISSUE THREAD

**Issue by catsigma** [OCamlPro/liquidity#209] opened 2019-04-14 09:05 UTC
```
Error: File "./tools/liquidity/liquidNamespace.ml", line 181, characters 46-52: Assertion failed
Backtrace:
Raised at file "map.ml", line 131, characters 10-25
Called from file "./tools/liquidity/liquidNamespace.ml", line 20, characters 6-33
```

Could it output the location where error occurs in liq file?

**Comment by catsigma** [comment] 2019-04-16 03:24
The issue seems to occur in such situation.

In `x.liq`, there is a sig `XSig` and the contract X uses this `XSig`.

In `lib.liq`, there is a inline function(named foo) which will call an X type contract.

In 'main.liq`, there is a call of `foo ()`, then it will cause this error.
But if `main.liq` call X type contract directly, then no errors will be shown and the compilation passes successfully.

**Comment by mebsout** [comment] 2019-07-09 14:13
Possibly duplicate of #213

**Closed by mebsout** 2019-07-09 14:13 UTC
